### ISSUE TITLE
float -> cssFloat

### ISSUE THREAD

**Issue by stevenvachon** [postcss/postcss-js#11]
I just updated [camelcase-css](https://npmjs.com/camelcase-css) to transform `float` to `cssFloat`. Could this cause an issue with this library?

I've created https://github.com/facebook/react/pull/6133 too.

**Comment by ai** [comment]
Yeap, we can add special case.

But what is a reason of `cssFloat`?

**Comment by stevenvachon** [comment]
What issue does it cause?

I added it because the purpose of the library is to convert dash-separated names to camel case for the purpose of CSS, which includes "gotchas".

**Comment by ai** [comment]
00f2d98

**Comment by stevenvachon** [comment]
Ah, I see. I didn't think about "stringifying".
