### ISSUE TITLE
How to fit with React?

### ISSUE THREAD

**Issue by zhaoyao91** [postcss/postcss-js#15]
e.g. 

```
prefixer({display:'flex'}) // => {display: ['flex', '-ms-flexbox']}
```

but react does not receive style as this format

**Comment by ai** [comment]
@zhaoyao91 what format is needed for React Inline Styles in this case?

**Comment by ai** [comment]
Also it is not a best idea to use React Inline Styles in this case. JSS, CSJS or other second-generation CSS-in-JS techniques is much better. And they supports two values with one property name.

**Comment by zhaoyao91** [comment]
I will check your solution, thanks
