### ISSUE TITLE
Webpack with PostCSS not working

### ISSUE THREAD

**Issue by thomaschaaf** [postcss/postcss-js#16]
I am trying to get postcss-js with webpack. I have tried the following:

    style-loader!css-loader!postcss-loader?parser=postcss-js!babel

In the generated js file I get the error message: The style-loader cannot be used in a non-browser environment (https://github.com/webpack/style-loader/issues/109)

Do you have a working configuration with webpack2?

**Comment by ai** [comment]
Ask webpack team :). Have no idea about `style-loader` :)
