### ISSUE TITLE
[TypeError: Cannot read property 'config' of null]

### ISSUE THREAD

**Issue by niksajanjic** [postcss/postcss-js#17]
I'm using Webpack and I'm following documentation for postcss-loader to add JS styles to my head tag. This is Webpack loader for this specific case:

```
{
  test: /\.base.style.js$/,
  loaders: [
    'style?singleton',
    'css?modules&importLoaders=1',
    'postcss?parser=postcss-js',
    'babel',
  ],
}
```

At first, I didn't use autoprefixer so I didn't have **postcss** property set inside my Webpack configuration and I would get above error. Once I added:

    postcss: [autoprefixer({ browsers: ['last 2 versions'] })]

The error disappeared. So, I thought I should mention that, only thing is that I'm not entirely sure is this right place where I should report it.

**Comment by ai** [comment]
Yeap, you should report it in `postcss-loader`.

We will fix it soon: https://github.com/postcss/postcss-loader/issues/115

This warning happens when you didn’t set any PostCSS plugins.

**Comment by ai** [comment]
Just use `postcss: []` until we will fix it :)
