### ISSUE TITLE
Cannot read property 'Base64' of undefined

### ISSUE THREAD

**Issue by corysimmons** [postcss/postcss-js#18]
I have a very bare bones React app I'm using Webpack 2 to bundle.

When I try to `import postcssJs from 'postcss-js'` the browser throws an `Uncaught TypeError: Cannot read property 'Base64' of undefined` in the bundle on `var _Base64 = global.Base64;`.

It works fine without the `import postcssJs` line. I'm sure I need some sort of globals loader or something but I'm new to Webpack and don't really understand how to do that with `import` statements (even after reading docs).

```js
module.exports = {
  entry: './demo/js/components/App.js',

  output: {
    path: __dirname + '/demo/js',
    filename: 'bundle.js'
  },

  module: {
    loaders: [
      {
        test: /\.(js|jsx)$/,
        loader: 'babel',
        query: {
          presets: [
            'es2015',
            'stage-0',
            'react'
          ],
          plugins: [
            'transform-react-stateless-component-name'
          ]
        }
      }
    ]
  },

  node: {
    fs: 'empty'
  },

  watch: true
}
```

```js
import React from 'react'

import postcssJs from 'postcss-js' // When I comment out this line, everything works fine.

export default ({greeting}) => <h3>{greeting}</h3>
```

Here is the full error in the browser:

```
bundle.js:12304 Uncaught TypeError: Cannot read property 'Base64' of undefined
    at bundle.js:12304
    at Object.<anonymous> (bundle.js:12440)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:19704)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:12827)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:20102)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:12542)
```

Here is the the line where it is throwing an error:

```js
// ...
/*
 * $Id: base64.js,v 2.15 2014/04/05 12:58:57 dankogai Exp dankogai $
 *
 *  Licensed under the MIT license.
 *    http://opensource.org/licenses/mit-license
 *
 *  References:
 *    http://en.wikipedia.org/wiki/Base64
 */

(function (global) {
    'use strict';
    // existing version for noConflict()

    var _Base64 = global.Base64; // THIS LINE
    var version = "2.1.9";
    // if node.js, we use Buffer
    var buffer;
    // ...
```

---

If I remove Babel from the equation, it works.

But I kind of need Babel...

**Comment by ai** [comment]
that is in the end of `(function (global) {`?

Also who requires this `base64` plugin?

Seems like it is a webpack issue, because it doesn’t set a `global` node.js’s env in right value.

**Comment by corysimmons** [comment]
https://github.com/corysimmons/postcss-ant/tree/refactor is where I'm at.

Here is the bundle: https://raw.githubusercontent.com/corysimmons/postcss-ant/refactor/demo/js/bundle.js

**Comment by ai** [comment]
Here is how webpack build `js-base64`:

```js
(function (global) {
    'use strict';
    // existing version for noConflict()

    var _Base64 = global.Base64;
    …
})(undefined);
```

So, seems like it is something wrong with your webpack config. You should ask webpack team for it.
