### ISSUE TITLE
Doesn't actually work with autoprefixer

### ISSUE THREAD

**Issue by herrstucki** [postcss/postcss-js#2]
autoprefixer [looks for `css.source.input.file`](https://github.com/postcss/autoprefixer/blob/master/lib/autoprefixer.coffee#L34) but `css.source` is undefined when used with postcss-js. But probably that's rather something which should be solved on autoprefixer's side?

**Comment by ai** [comment]
Yeap, it is a issue in Autoprefixer. I will it on this weekend.

**Comment by herrstucki** [comment]
Nice, thanks!

**Comment by ai** [comment]
Fixed https://github.com/postcss/autoprefixer/commit/1bb880409c89de33a8a51a4a8741db6f1c6e46cd

Sorry, I already made next 6.1 release commits to Autoprefixer repo, so you need to wait this release. But it almost done, just few issue.
