### ISSUE TITLE
Usage with postcss-cli?

### ISSUE THREAD

**Issue by nwmcsween** [postcss/postcss-js#23]
As per the title how can one use postcss-js with postcss-cli? Can you pass options for plugins before postcss-js?

**Comment by ai** [comment]
@RyanZim I think we need special support for `--parser postcss-js`, because we need to `require()` file instead of reading it by `fs`.

What do you think?

**Comment by RyanZim** [comment]
@ai Sorry, I'm not real familiar with postcss-js; I'm not getting why you would want to use this with the CLI. Would this be to require a CSS-in-JS file and convert it to CSS?

**Comment by ai** [comment]
@RyanZim yeap. Input file is:

```js
module.exports = {
  a: {
    color: 'red'
  }
}
```

On `postcss-cli --parser postcss-js ./style.js` output should be:

```css
a {
  color: red
}
```

**Comment by RyanZim** [comment]
OK, I see your point; what about when someone wants to convert CSS to JS?

    postcss --stringifier postcss-js input.css -o myCSS.js

I'm not saying we should support this, just saying I can see someone asking for this sometime.

**Comment by ai** [comment]
Good question. It will be cool to support it, but I am not sure, that users will use it :D. So up to you:

1. Do not implement it and show warning.
2. Stringify it by `"module.exports = " + JSON.stringify(js, 4)`.

**Comment by RyanZim** [comment]
I don't really want to support the stringifier that way; if postcss-js exposed a `stringify` function though, it would work with postcss-cli out of the box.

Either way, I'd be willing to special-case `--parser postcss-js`; but I want v3.0.0 shipped first. Perhaps v3.1? If you don't mind, open an issue at postcss-cli so I don't forget about this. Thanks!

**Comment by ai** [comment]
@RyanZim sure. could you create a issue to track process?

**Comment by michael-ciniawsky** [comment]
### Parser

```bash
postcss style.js -p postcss-js
```

```js
if (path.extname(file) === '.js') {
  return Promise.resolve(require('file'))
    .then((content) => css(content))
}
```

### Stringifier

```bash
postcss style.css -t postcss-js -o style.js
postcss style.css -t postcss-js --ext .js
```

```js
if (path.extname(output) === '.js' || argv.ext === '.js') {
  fs.outputFile(options.to, `module.exports = ${JSON.stringify(result.css, 2)}`)
}
```

**Comment by ai** [comment]
@RyanZim changes are small =^_^=
