### ISSUE TITLE
Cannot work with DevDependencies. Has a big footprint

### ISSUE THREAD

**Issue by antoninadert** [postcss/postcss-js#28]
Hello,

I just tried to use this autoprefixer for CSS-in-JS and made it work (by the way, it was not so easy since it is not written that we should import both autoprefixer and this package to make it work)

The problem is that it is not executed with postcss, so I need to change my code everywhere I have inline styles.

The package is also big, (100kB gzipped) and it forces me to put autoprefixer as a real dependency (so now it ships with like 300kB gzipped)

This is not acceptable for me. 

Do you think there are other available solutions? 
Or maybe there is a way to make it work as a standard PostCSS thing? 

Thanks in advance

**Comment by ai** [comment]
PostCSS and Autoprefixer was designed to be run in deployment, not in on the client-side.

Anyway running Autoprefixer again and again on client-side is a bad idea for performance.

Check Emotion.js staticMode how you can combine PostCSS with CSS-in-JS.
