### ISSUE TITLE
camelcase-css dependency is not es5 compatible

### ISSUE THREAD

**Issue by gregplaysguitar** [postcss/postcss-js#33]
Everything in this lib works perfectly on es5-only browsers, except camelcase-css which uses non-transpiled `const` and arrow functions. The maintainer of that lib doesn't want to change it (see https://github.com/stevenvachon/camelcase-css/pull/2), so there's two options I can see

1. Fork camelcase-css (perhaps as camelcase-css-es5) and use that instead
2. Inline the code from camelcase-css

Very happy to do the work to fix this but wanted to get some maintainer feedback first. Let me know what you think.

**Comment by ai** [comment]
I like the idea of Inlining the code from `camelcase-css`.

Do you want to send PR?

**Comment by gregplaysguitar** [comment]
Sure, happy to do that - I'll give the camelcase-css maintainer a day or so, and if he doesn't change his mind will do.

**Comment by macklinu** [comment]
Was this resolved with the update to `camelcase-css@2.0.1` in 3eb19af05c43150adbd15dbdb069dc497d265502?
