### ISSUE TITLE
the output is not the result  which i want.

### ISSUE THREAD

**Issue by pengliheng** [postcss/postcss-js#34]
![image](https://user-images.githubusercontent.com/14355994/47964986-e60cd500-e07b-11e8-871f-d84cc2737393.png)

i want to output  
```json
{ display: ['-webkit-box', '-webkit-flex', '-ms-flexbox', 'flex'] }
```

but it output
```json
{ display: 'flex' }
```

i have read all the readme file, but can't output the text which i want

**Comment by ai** [comment]
Flexbox doesn't need prefixes for modern browsers anymore.

If you want to test Autprefixer, use `userSelect: 'none'`.

I will update example.

**Comment by pengliheng** [comment]
thx a log ,i fix my problem

**Comment by ai** [comment]
https://github.com/postcss/postcss-js/commit/ea0414546948bb9822b2afcc7ca9ebb8546d30e3
