### ISSUE TITLE
objectifier.process nested loop

### ISSUE THREAD

**Issue by hcomnetworkers** [postcss/postcss-js#37]
Is there any particular reason, why the `node.each` is nested in objectifier.process?
https://github.com/postcss/postcss-js/blob/master/objectifier.js#L16

It does not seem that this inner loop is using `child` nor is it affecting the rest of the outer loop in a scoped manner.

**Comment by ai** [comment]
Fixed ab12318

**Comment by ai** [comment]
Released in 2.0.1
