### ISSUE TITLE
objectifier should be a pure function

### ISSUE THREAD

**Issue by hcomnetworkers** [postcss/postcss-js#38]
objectifier is manipulating the input node, this can cause problems when calling it multiple times.

In particular when `!important` declarations are included, multiple calls to objectify will yield different results because the `child.value` is mutated: https://github.com/postcss/postcss-js/blob/master/objectifier.js#L43

The objectifier should not have side effects.

**Comment by ai** [comment]
Fixed 3ba9103

**Comment by ai** [comment]
Released in 2.0.1
