### ISSUE TITLE
Use plugins from postcss.config.js

### ISSUE THREAD

**Issue by Yzrsah** [postcss/postcss-js#39]
Is it possible to use the plugins that are already loaded in `postcss.config.js`?

I am using postcss-js manually:
```
const myPlugin = require("postcss-myplugin");
const syncMyPlugin = postcssJs.sync([myPlugin]);
const postcssProcess = style => syncMyPlugin({ root: style }).root;
```

Instead I want to use the plugins that are already loaded in `postcss.config.js` and write:
```
const postcssProcess = style => postcssJs.sync([])({ root: style }).root;
```

or:
```
postcssJs.doAllTheStuff(style);
```

**Comment by ai** [comment]
Use this library to load plugins list

https://github.com/michael-ciniawsky/postcss-load-config/blob/master/README.md

**Comment by Yzrsah** [comment]
@ai 

Yes I am already using `postcss-load-config` and `postcss-loader` I have loaded my plugins and everything works as usual.

But postcss-js does not utilize it. Do you have any example? I'm not sure what you mean.

**Comment by ai** [comment]
The base API:

```js
const postcssrc = require('postcss-load-config')

postcssrc().then(({ plugins }) => {
  postcssJs(plugins) …
})
```

What input/output do you want to get?
