### ISSUE TITLE
Isomorphic/Universal app support?

### ISSUE THREAD

**Issue by rej156** [postcss/postcss-js#4]
Since the postcss module that converts css to css-in-js objects afaik is not isomorphic?

**Comment by ai** [comment]
@rej156 why it is not isomorphic? It do not use any browser API and node.js modules is not required.

**Comment by rej156** [comment]
In the example, in the README.
let css  = '@media screen { z-index: 1 }'
let root = postcss.parse(css);

^^^ postcss.parse brings up errors clientside?

**Comment by ai** [comment]
@rej156 what error?
