### ISSUE TITLE
DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at G:\SNWS\sn-micro-front-web-project-template\node_modules\postcss-js\package.json.

### ISSUE THREAD

**Issue by LP1994** [postcss/postcss-js#50]
This is not a error!!!

operating system: Windows 10,
node: 15.1.0,
npm: 6.14.8,
webpack: 5.4.0,
postcss: 8.1.4,
postcss-js: 3.0.1.

This is only a warning issued by "nodejs". It is recommended to make corrections according to the warning, because some writing methods are not recommended.
![image](https://user-images.githubusercontent.com/12012671/98194825-38c74300-1f5b-11eb-9898-b3e008ff3a64.png)

**Comment by ai** [comment]
Fixed fa27b70

**Comment by ai** [comment]
Released in 3.0.2

**Comment by LP1994** [comment]
> Released in 3.0.2

Warnings still appear in "postcss-js v3.0.3".

**Comment by ai** [comment]
I moved issue to the single place https://github.com/postcss/postcss/issues/1455
