### ISSUE TITLE
Help needed for implementing with Vite

### ISSUE THREAD

**Issue by ivanjeremic** [postcss/postcss-js#58]
I came across this plugin and it seems it does exactly what I want, the problem is I can't find any information on how to implement it with Vite build tool, Is it possible, and what would be the steps?

Also, how is the generation of classes happening is this something I need to handle on my own in my custom framework?

Thanks

**Comment by ai** [comment]
Hi, again.

As I told in PostCSS chat you need to speak with Vite community. I don’t use Vite to help you here.

**Comment by ivanjeremic** [comment]
Ok thanks but even if I use Webpack I can't see much information on how to integrate this plugin.

**Comment by ai** [comment]
It is a internal tool for CSS tool authors.

It can't be used simply by changing PostCSS config.

I show API in docs, but you need to find on your own, how do you want to integrate this API in you processing tools.

Seems like your task can't be solved just with this tool and you need some other wrappers.
