### ISSUE TITLE
Not working with rtlcss?

### ISSUE THREAD

**Issue by rtsao** [postcss/postcss-js#6]
It seems postcss-js isn't working with rtlcss:

```javascript
var postcss = require('postcss-js');
var rtlcss = require('rtlcss');
var autoprefixer = require('autoprefixer');

var process = postcss.sync([ rtlcss, autoprefixer ]);

var css = {
  borderColor: 'red green blue black',
  left: '5px',
  transition: 'width 5s ease'
};

console.log(process(css));
/*
{
  borderColor: 'red green blue black',
  left: '5px',
  WebkitTransition: width 5s ease,
  transition: 'width 5s ease'
}
*/
```

Example: http://requirebin.com/?gist=c3c2359607da757c4263

**Comment by ai** [comment]
@rtsao maybe it is because declaration has no rule. But it should be RTLCSS issue anyway.

Maybe we need to open issue in RTLCSS repo.

**Comment by rtsao** [comment]
Adding the styles into a class doesn't seem to change anything. I made an issue with rtlcss:

https://github.com/MohammadYounes/rtlcss/issues/48
