### ISSUE TITLE
Use of deprecated folder mapping "./" in the "exports" 

### ISSUE THREAD

**Issue by nowaysgit** [postcss/postcss-js#63]
[DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Use
rs\noways\Desktop\nfc-tag-vova\site\client\node_modules\postcss-autoreset\node_modules\postcss-js\package.json.
Update this package.json to use a subpath pattern like "./*".

**Comment by ai** [comment]
We don’t have `./` in `exports`. https://github.com/postcss/postcss-js/blob/main/package.json#L25-L34

Maybe you are using old `postcss-js`?
