### ISSUE TITLE
package.json Error, Deprecationwarning

### ISSUE THREAD

**Issue by HuakunShen** [postcss/postcss-js#65]
<img width="609" alt="image" src="https://user-images.githubusercontent.com/33727687/160256724-ed68e822-3644-408f-b1ff-064fb4f19585.png">

```
ERROR 

(node:5686) [DEP0148] DeprecationWarning: Use of deprecated
folder mapping "./" in the "exports" field module resolution of
 the package at /Users/<...>/node_module
s/postcss-js/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning
was created)
```

**Comment by ai** [comment]
You are using old `postcss-js`

https://github.com/postcss/postcss-js/blob/main/package.json#L25-L34=

Use `npm ls` to find who use old `postcss-js` and ask them to update.
