### ISSUE TITLE
Support Node v18

### ISSUE THREAD

**Issue by daniellacosse** [postcss/postcss-js#73]
Package subpaths are no longer supported in Node v18: https://github.com/maximkoretskiy/postcss-autoreset/issues/37

Node v16 is approaching end of life this year, so this is critical. Everything depending on your package will break.

**Comment by ai** [comment]
Node.js 18 and 20 both should support `package.exports` with [this syntax](https://github.com/postcss/postcss-js/blob/main/package.json#L24-L35)

What do you mean by package subpaths? How do you plan to fix it?
