### ISSUE TITLE
How to skip camelCase property name

### ISSUE THREAD

**Issue by eduardocque** [postcss/postcss-js#76]
Hi,

Is there a way to skip the camelCase transformation for the variable names ?

```
 const root = postcss.parse(css);
 const cssJs = postcssJs.objectify(root);
```

im trying to find a way to skip the camelCase in the moment that i do the objectify, was thinking if is possible to introduce a property to enable/disable it

is that possible ?

**Comment by ai** [comment]
There is no way except copying `objectify` and changing the code

**Comment by eduardocque** [comment]
thanks @ai
