### ISSUE TITLE
Issue with flex:none

### ISSUE THREAD

**Issue by eduardocque** [postcss/postcss-js#77]
Hi @ai, testing this noticed a bug, when we try to convert the next css

`.flex-none{flex:none}` to object is returning`{ '.flex-none': { flex: NaN } }`

when this supose to be
`{ '.flex-none': { flex: 'none' } }`

seems to be an issue here https://github.com/postcss/postcss-js/blob/main/objectifier.js#L69 where we are not evaluating if flex is `'none'` making this css corrupted

if we try to parse `parseFloat('none')` will be `NaN`

Regards

**Comment by ai** [comment]
Can you send PR with fix and test?

**Comment by eduardocque** [comment]
testing deeper, was my mistake, seems to be that `Number.isNaN` is not the same as `isNaN` directly when i was testing, will check what is the difference between both
