### ISSUE TITLE
Question about webpack usage

### ISSUE THREAD

**Issue by rmwdeveloper** [postcss/postcss-js#78]
I would like to author my styles as regular objects and pass them to postcss + postcss-js.

Here is the relevant portion from my webpack config. This is an excerpt from the module.rules array

```json
{
  "test": /\.css.ts$/,
  "use": [
    "style-loader",
    {
      "loader": "css-loader",
      "options": {
        "importLoaders": 1
      }
    },
    {
      "loader": "postcss-loader",
      "options": {
        "implementation": "postcss",
        "postcssOptions": {
          "parser": "postcss-js"
        }
      }
    },
    "ts-loader"
  ]
}
``` 

And here is the file that is being processed by the webpack rule in question

Button.css.ts
```typescript
import { Button } from '../styles/Button.styles';

const styles = {
    '.Button': Button
}
export default styles;
```

Button.styles.ts

```typescript
export const Button: CSSObject = {
    display: 'inline-flex'
}
```

Looking at postcss-js' documentation, it appears that it is expecting just a plain object, but of course ts-loader outputs what the typescript compiler emits for that single file, import declarations and all.

I believe I need an intermediate loader between ts-loader and postcss-loader that evaluates what ts-loader returns, extracts the value of the default export, and returns that.
 

I can sort of get it working by changing the postcss loader in my rule to this

```typescript
{
  "loader": "postcss-loader",
  "options": {
    "implementation": "postcss",
    "postcssOptions": {
      "parser": function(_, file) {
        const code = require(file.from);
        const postcssjs = require('postcss-js');
        const parsed = postcssjs.parse(code.default);
        return parsed;
      }
    }
  }
}
```

With this, the hot module reloading doesn't work since the require is happening outside of webpack's context.

I have also tried val-loader, but I would rather not have to format my exports in a particular way (exporting a function that returns an object with a 'code' key).

**Comment by ai** [comment]
We do not plan this module to be used in webpack as-is.

It is a low-level module to create a custom tools on top.

You need special extra work to make it work with hot reload. If the fix is small, you can send PR back to the project.
