### ISSUE TITLE
Use JSON values from file/API?

### ISSUE THREAD

**Issue by kevinSuttle** [postcss/postcss-js#9]
Is something like this possible?
https://viget.com/extend/sharing-data-between-sass-and-javascript-with-json

**Comment by ai** [comment]
You don’t need even a `postcss-js` for it. For example, [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars) accepts a `variables` option. So yo can do:

`gulpfile.js` or `webpack.config.js`:

```js
let vars = require('./global/colors');
var plugins = [simpleVars({  options: { variables: variables } })]
```

`global/colors.json`:

```json
{
  "red"  : "#c33",
  "blue" : "#33c"
}
```

`components/logo/logo.css`:

```css
.logo {
    color: $red
}
```

**Comment by kevinSuttle** [comment]
Nice! Thanks!
